---
- name: Update system packages
  hosts: all
  become: yes
  tasks:
    - name: Update packages on Debian-based systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update packages on AlmaLinux (RHEL-based) systems
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
